# Generated by Django 3.2.5 on 2023-01-13 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='firstBid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstBid', to='auctions.bid'),
        ),
    ]
