# Generated by Django 3.2.5 on 2023-02-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.IntegerField(default=0)),
                ('pages', models.IntegerField(default=0)),
            ],
        ),
    ]
